services:
  postgres:
    image: postgres:13
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: swift
      POSTGRES_USER: swift
      POSTGRES_PASSWORD: swift
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      qbft_testnet:
        ipv4_address: 10.42.0.10

  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka-broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: OaZ6qrUNLdj9
    networks:
      qbft_testnet:
        ipv4_address: 10.42.0.11

  akhq:
    image: tchiotludo/akhq
    restart: unless-stopped
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"
    ports:
      - 8080:8080
    links:
      - kafka
    networks:
      qbft_testnet:
        ipv4_address: 10.42.0.12

  kcat:
    image: edenhill/kcat:1.7.1
    entrypoint: ["sh", "-c"]
    command:
      - "sleep 10 ; echo -e 'foobar1\nfoobar2' | kcat -b kafka:29092 -t swiftnet -T -P"
    networks:
      qbft_testnet:
        ipv4_address: 10.42.0.13
    links:
      - kafka
    depends_on:
      - kafka

  validator1:
    image: hyperledger/besu:latest
    command: [ "--config-file=/opt/besu/common-config.toml",
               "--identity=validator1",
               "--p2p-host=10.42.0.2",
               "--p2p-port=30303" ]
    configs:
      - source: besu-genesis
        target: /opt/besu/genesis.json
        uid: "1000"
        gid: "1000"
      - source: besu-common-config
        target: /opt/besu/common-config.toml
        uid: "1000"
        gid: "1000"
      - source: besu-validator1-key
        target: /opt/besu/key
        uid: "1000"
        gid: "1000"
    volumes:
      - validator1-data:/opt/besu/data
    ports:
      - "8545:8545"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    networks:
      qbft_testnet:
        ipv4_address: 10.42.0.2

  validator2:
    image: hyperledger/besu:latest
    command: [ "--config-file=/opt/besu/common-config.toml",
               "--identity=validator2",
               "--bootnodes=enode://ad83ac93fcc30a30f3e1bb6467623e45719167be50d13dccd8361cbca478cb540069869d1bae16de0f8b17a28f26f1c6c4dc12e71f240b366c6ff6f02f3fb93e@10.42.0.2:30303",
               "--p2p-host=10.42.0.3",
               "--p2p-port=30304" ]
    configs:
      - source: besu-genesis
        target: /opt/besu/genesis.json
        uid: "1000"
        gid: "1000"
      - source: besu-common-config
        target: /opt/besu/common-config.toml
        uid: "1000"
        gid: "1000"
      - source: besu-validator2-key
        target: /opt/besu/key
        uid: "1000"
        gid: "1000"
    volumes:
      - validator2-data:/opt/besu/data
    ports:
      - "8546:8545"
      - "30304:30304/tcp"
      - "30304:30304/udp"
    networks:
      qbft_testnet:
        ipv4_address: 10.42.0.3

  validator3:
    image: hyperledger/besu:latest
    command: [ "--config-file=/opt/besu/common-config.toml",
               "--identity=validator3",
               "--bootnodes=enode://ad83ac93fcc30a30f3e1bb6467623e45719167be50d13dccd8361cbca478cb540069869d1bae16de0f8b17a28f26f1c6c4dc12e71f240b366c6ff6f02f3fb93e@10.42.0.2:30303",
               "--p2p-host=10.42.0.4",
               "--p2p-port=30305" ]
    configs:
      - source: besu-genesis
        target: /opt/besu/genesis.json
        uid: "1000"
        gid: "1000"
      - source: besu-common-config
        target: /opt/besu/common-config.toml
        uid: "1000"
        gid: "1000"
      - source: besu-validator3-key
        target: /opt/besu/key
        uid: "1000"
        gid: "1000"
    volumes:
      - validator3-data:/opt/besu/data
    ports:
      - "8547:8545"
      - "30305:30305/tcp"
      - "30305:30305/udp"
    networks:
      qbft_testnet:
        ipv4_address: 10.42.0.4

  validator4:
    image: hyperledger/besu:latest
    command: [ "--config-file=/opt/besu/common-config.toml",
               "--identity=validator4",
               "--bootnodes=enode://ad83ac93fcc30a30f3e1bb6467623e45719167be50d13dccd8361cbca478cb540069869d1bae16de0f8b17a28f26f1c6c4dc12e71f240b366c6ff6f02f3fb93e@10.42.0.2:30303",
               "--p2p-host=10.42.0.5",
               "--p2p-port=30306" ]
    configs:
      - source: besu-genesis
        target: /opt/besu/genesis.json
        uid: "1000"
        gid: "1000"
      - source: besu-common-config
        target: /opt/besu/common-config.toml
        uid: "1000"
        gid: "1000"
      - source: besu-validator4-key
        target: /opt/besu/key
        uid: "1000"
        gid: "1000"
    volumes:
      - validator4-data:/opt/besu/data
    ports:
      - "8548:8545"
      - "30306:30306/tcp"
      - "30306:30306/udp"
    networks:
      qbft_testnet:
        ipv4_address: 10.42.0.5

configs:
  besu-genesis:
    content: |
      {
        "config" : {
          "chainId" : 1337,
          "cancunTime" : 0,
          "zeroBaseFee" : true,
          "qbft" : {
            "blockperiodseconds" : 2,
            "epochlength" : 30000,
            "requesttimeoutseconds" : 4
          }
        },
        "nonce" : "0x0",
        "timestamp" : "0x58ee40ba",
        "gasLimit" : "0x1c9c380",
        "difficulty" : "0x1",
        "mixHash" : "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
        "coinbase" : "0x0000000000000000000000000000000000000000",
        "alloc" : {
          "fe3b557e8fb62b89f4916b721be55ceb828dbd73" : {
            "privateKey" : "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63",
            "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
            "balance" : "0xad78ebc5ac6200000"
          },
          "627306090abaB3A6e1400e9345bC60c78a8BEf57" : {
            "privateKey" : "c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
            "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
            "balance" : "90000000000000000000000"
          },
          "f17f52151EbEF6C7334FAD080c5704D77216b732" : {
            "privateKey" : "ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f",
            "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
            "balance" : "90000000000000000000000"
          },
          "da6c0ca76e69b32c71301356043fb56d702dfb3d" : {
            "mnemonic" : "exit warm sadness vault clip rent educate pluck gentle vehicle news verb",
            "comment" : "mnemonic and this comment are ignored.  In a real chain, the private key should NOT be stored",
            "balance" : "90000000000000000000000"
          }
        },
        "extraData" : "0xf87aa00000000000000000000000000000000000000000000000000000000000000000f85494065f139d8a49e9926232cc4435159024cb5064fc940eb968de631abc65322ecdca5dfdf9c6296e52f494543d3796700ee35803a1c43562a69fec08e1e4239420c5edbcf6263cd9e30df395a2b914f6e939b9bac080c0"
      }
  besu-common-config:
    content: |
      genesis-file="/opt/besu/genesis.json"
      data-path="/opt/besu/data"
      node-private-key-file="/opt/besu/key"
      rpc-http-enabled=true
      rpc-http-api=["ETH","QBFT","WEB3", "DEBUG"]
      host-allowlist=["*"]
      rpc-http-cors-origins=["all"]
      tx-pool="legacy"
      tx-pool-limit-by-account-percentage=1.0
      tx-pool-max-size="1000000"
  besu-validator1-key:
    content: |
      0x18fddb41c4f6316532162f1c54a0cf4c62562b499c392720f04e7d33e32e88fa
  besu-validator2-key:
    content: |
      0x9a4cc956527624fba01e932a28f982233b8169d840b72a9089cd0d3da127ccb6
  besu-validator3-key:
    content: |
      0x2fd21d48dcb473933de188ff882fed9d3bcbc4d43af77172f1b8035f1574a19b
  besu-validator4-key:
    content: |
      0xa9b2b5406572152ceb0a5480a65f63fc562e6970402dd58ede1bec32837ae25a

networks:
  qbft_testnet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 10.42.0.0/16
          gateway: 10.42.0.1

volumes:
  postgres-data:
    driver: local
  validator1-data:
    driver: local
  validator2-data:
    driver: local
  validator3-data:
    driver: local
  validator4-data:
    driver: local
